### ISSUE TITLE
passphrase.io server can easily guess the used password

### ISSUE THREAD

**Issue by sgeisler** [routman/passphrase.io#1]
The text associated with the hash of a given passphrase gets loaded every time a character is typed in the password field (if you don't type >5 characters per second). So while I type in my password (abcd) the server sees the hashes of the password parts. First `hash("a")` then `hash("ab")`, `hash("abc")` and finally `hash("abcd")`. So at every stage the password can be guessed using maximum 256 tries. This leads to a complexity of O(n*256) for cracking a password of length n instead of O(256^n) (actually it's even worse since you typically don't use all 256 possible values for a byte in text).

```
		$("#phrase").keyup(function(){
			clearTimeout(timer);
			$('#save').val('loading...');
			var target = $(this);

			timer = setTimeout(function() {
				getText();	
			}, 200);
		});
```
[script.js:61](https://github.com/routman/passphrase.io/blob/master/js/script.js#L61)

![passphrase_io](https://cloud.githubusercontent.com/assets/1876998/13206827/3a8fa22c-d906-11e5-89ed-6930daaad053.png)

**Comment by routman** [comment]
That's why there is a setTimeout function.  If you type rapidly, the hash only gets sent one time after you are done typing.

**Comment by routman** [comment]
The current version of passphrase.io no longer loads content as you type, and no longer uses one round of SHA256.  There is now a "load" button that the user must click, which computes a memory-intensive scrypt key.
