### ISSUE TITLE
Not fully open source

### ISSUE THREAD

**Issue by agarzon** [routman/passphrase.io#5]
I saw this as an awesome idea, until I saw the script makes private calls to https://passphrase.io/ so it will always depend on https://passphrase.io/ to be up and running, even worst: we will never know what information is being collected there.

So not having the source of gettext.php and savetext.php makes this application extremely unsafe.

**Comment by routman** [comment]
Passphrase.io is an **online** notepad.  Of course it makes calls to passphrase.io.  

You do know what information is being collected there: the hash and the ciphertext.  This is clearly visible in the source code, and you can verify it by monitoring network traffic using the developer tools in your web browser.

I did not publish the source code for database read/write operations for two reasons:  1. It would be a security risk to reveal the structure of the database and methods used to interact with the database.  2. It's extraneous.  Notepad storage can be done using any database, and the scripts are about as simple as they get (reading and writing data to a database).

I strongly disagree with your claim that the application is "extremely unsafe", and I do not consider any of your claims to be valid.

**Comment by nashe** [comment]
> It would be a security risk to reveal the structure of the database and methods used to interact with the database

Can you explicit?
